### ISSUE TITLE
sort command failing in run_test_SMp.sh 

### ISSUE THREAD

**Issue by biominer** [fanglab/SMALR#6] opened 2017-10-20 04:36 UTC
Hi John,

Great package and well-written paper, I'm looking forward to getting this working.

Installation and setting up the virtual environment went fine, but upon running the test scripts, I'm receiving an error for the sort command failing for some reason. Please see below to see if anything jumps out as the possible source of the error.

Many thanks,
---Sam 

	- ref000002 (scf7180000000009|quiver)
	- ref000001 (scf7180000000008|quiver)
	- ref000003 (scf7180000000010|quiver)
	- ref000004 (scf7180000000011|quiver)
21:29:35 [INFO] 
21:29:35 [INFO] ====================================
21:29:35 [INFO] Analyzing contig ref000002 (scf7180000000009|quiver)
21:29:35 [INFO] ====================================
21:29:35 [INFO] ref000002 - contig_id:               ref000002
21:29:35 [INFO] ref000002 - contig_name:             scf7180000000009|quiver
21:29:36 [INFO] Partitioning /home/smodlin/projects/SMALR/SMALR/test/wga_longlib.cmp.h5 into 4 chunks for analysis...
21:29:36 [INFO] ...chunk 2 - 0/2 (0.0%) alignments processed...
21:29:36 [INFO] ...chunk 1 - 0/1 (0.0%) alignments processed...
21:29:36 [INFO] ...chunk 0 - 0/8 (0.0%) alignments processed...
21:29:36 [INFO] ...chunk 3 - 0/4 (0.0%) alignments processed...
21:29:36 [INFO] ...chunk 0 - 4/8 (50.0%) alignments processed...
21:29:36 [INFO] ref000002 - Combining the 4 separate ipdArray dictionaries...
21:29:36 [INFO] Partitioning /home/smodlin/projects/SMALR/SMALR/test/nat_longlib.cmp.h5 into 4 chunks for analysis...
21:29:36 [INFO] ref000002 - Separating out file-matched regions of the control IPD values dict...
21:29:36 [INFO] ...chunk 0 - processing molecules: 0/1 (0.0%)
21:29:36 [INFO] ...chunk 1 - processing molecules: 0/4 (0.0%)
21:29:36 [INFO] ...chunk 2 - processing molecules: 0/1 (0.0%)
21:29:36 [INFO] ...chunk 3 - processing molecules: 0/1 (0.0%)
21:29:36 [INFO] ref000002 - Combining chunked test output files...
21:29:36 [INFO] ref000002 - Finalizing cleanup...
21:29:36 [INFO] Sorting output by strand/position...
Traceback (most recent call last):
  File "/home/smodlin/projects/SMALR/smalr_venv/bin/call_smalr.py", line 4, in <module>
    __import__('pkg_resources').run_script('smalr==1.0.0', 'call_smalr.py')
  File "/home/smodlin/projects/SMALR/smalr_venv/local/lib/python2.7/site-packages/pkg_resources.py", line 534, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/smodlin/projects/SMALR/smalr_venv/local/lib/python2.7/site-packages/pkg_resources.py", line 1438, in run_script
    execfile(script_filename, namespace, namespace)
  File "/home/smodlin/projects/SMALR/smalr_venv/lib/python2.7/site-packages/smalr-1.0.0-py2.7.egg/EGG-INFO/scripts/call_smalr.py", line 5, in <module>
    sys.exit(main())
  File "/home/smodlin/projects/SMALR/smalr_venv/local/lib/python2.7/site-packages/smalr-1.0.0-py2.7.egg/smalr/smalr_multicontig.py", line 86, in main
    sys.exit( app.run() )
  File "/home/smodlin/projects/SMALR/smalr_venv/local/lib/python2.7/site-packages/smalr-1.0.0-py2.7.egg/smalr/smalr_multicontig.py", line 81, in run
    runner.run()
  File "/home/smodlin/projects/SMALR/smalr_venv/local/lib/python2.7/site-packages/smalr-1.0.0-py2.7.egg/smalr/smalr.py", line 392, in run
    raise Exception("Failed sort command: %s" % sort_CMD)
Exception: Failed sort command: sort -t$'\t' -nk2 SMp.out > sorting.tmp

**Comment by jbeaulaurier** [comment] 2017-10-26 23:56
Hello Sam,

Sorry for the delay getting back to you. Can you tell me: is the SMp.out file being created? I'm guessing not, and this is breaking the sort command. Could you try running that same command in SMp test debug mode? You can do this by just replacing "-i" in the run_test_SMp.sh file with "-d". Please copy/paste the output from that command and I'll see if that exposes the root cause of the problem.

Thanks for using SMALR!
-John

**Comment by jbeaulaurier** [comment] 2018-01-02 23:20
Should be fixed by commit 34cce4b.

**Closed as completed by jbeaulaurier** 2018-01-02 23:20 UTC
